version: "3.8"
services:
  php:
    build:
      context: ./docker/php
    depends_on:
      - mysql
    volumes:
      - ./backend:/var/www/html:cached
      - ./docker/php/socket:/var/run/php-fpm
      - ./docker/mysql/socket:/var/run/mysqld
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./frontend:/var/www/html:cached
  web:
    build:
      context: ./docker/nginx
    depends_on:
      - php
    ports:
      - 85:80
    volumes:
      - ./backend:/var/www/html:cached
      - ./docker/logs/nginx:/var/log/nginx
      - ./docker/php/socket:/var/run/php-fpm
  mysql:
    build:
      context: ./docker/mysql
    ports:
      - 3309:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - ./docker/logs/mysql:/var/log/mysql:cached
      - small-sns-db:/var/lib/mysql:cached
      - ./docker/mysql/socket:/var/run/mysqld
    environment:
      MYSQL_DATABASE: sns
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data
    command: redis-server
volumes:
  small-sns-db:
